### ISSUE TITLE
Add Docker compose integration?

### ISSUE THREAD

**Issue by Aristarhys** [docker-slim/docker-slim#116]
Hi, i just wondering if it possible build slim image for using on `docker-compose up --build --detach` if every compose service is bulding from some custom Dockerfile.
```
 srv-redis:
    build: src/redis
    container_name: srv-redis
    ports:
    - 6379
```
