### ISSUE TITLE
`channel.NewCommandClient: NewClient error = wait timeout` on Gitlab CI

### ISSUE THREAD

**Issue by openedhardware** [docker-slim/docker-slim#177]
I have been pulling my hairs out to get docker-slim working on gitlab CI.
Here is my .gitlab-ci.yml file:
```
stages:
  - test
  - build-amd64

variables:
  DOCKER_DRIVER: overlay2

test:
  image: python:3.7
  script:
    - pip install flake8
    - flake8 .

build-amd64:
  image: docker
  stage: build-amd64
  dependencies:
    - test
  timeout: 2 hours
  services:
    - name: docker:18.09.7-dind
  before_script:
    - wget https://downloads.dockerslim.com/releases/$DOCKER_SLIM_VERSION/dist_linux.tar.gz && tar zxvf dist_linux.tar.gz && cp -R dist_linux/* /usr/local/bin/
  script:
    - docker build -t local -f Dockerfile.cpu .
    - mkdir $(pwd)/viso
    - docker volume ls && docker images
    - docker-slim build --http-probe=false --continue-after 1 --network=host --mount $(pwd)/viso:/viso --include-path /usr/local/lib/python3.6/dist-packages/certifi --show-clogs local
```

But it fails to build. Output is:
```
<Docker image build here>
... ... ...
Successfully built 34c6a82094c3
Successfully tagged local:latest
$ mkdir $(pwd)/viso
$ docker volume ls && docker images
DRIVER    VOLUME NAME
local     374a844866318ca84fa87f7677b980266933e8d5ca8e320faaf38dcb5799ecbc
local     runner-7sma5fqk-project-15065848-concurrent-0-cache-3c3f060a0374fc8bc39395164f415a70
local     runner-7sma5fqk-project-15065848-concurrent-0-cache-c33bcaa1fd2c77edfc3893b41966cea8
REPOSITORY                    TAG               IMAGE ID       CREATED                  SIZE
local                         latest            34c6a82094c3   Less than a second ago   2GB
gitlab/gitlab-runner-helper   x86_64-4e1f20da   60efe6e10bba   12 minutes ago           60.9MB
docker                        latest            6e081696197d   4 hours ago              241MB
python                        3.7               eb8410fd55d8   6 hours ago              876MB
tensorflow/tensorflow         2.3.1             a6528f3f080b   7 weeks ago              1.47GB
docker                        18.09.7-dind      25a1e57c7741   19 months ago            184MB
$ docker-slim build --http-probe=false --continue-after 120 --network=host --mount $(pwd)/viso:/viso --include-path /usr/local/lib/python3.6/dist-packages/certifi --show-clogs local
docker-slim: message='join the Gitter channel to ask questions or to share your feedback' info='https://gitter.im/docker-slim/community'
docker-slim: message='join the Discord server to ask questions or to share your feedback' info='https://discord.gg/9tDyxYS'
docker-slim: message='Github discussions' info='https://github.com/docker-slim/docker-slim/discussions'
cmd=build state=started
cmd=build info=params target=local continue.mode=timeout rt.as.user=true keep.perms=true
cmd=build state=image.inspection.start
cmd=build info=image id=sha256:34c6a82094c31dcd49a2bae532de2fe9a0bc2d96d842e60473c0f9dff9e56332 size.bytes=2002330020 size.human=2.0 GB
cmd=build info=image.stack index=0 name='tensorflow/tensorflow:2.3.1' id='sha256:a6528f3f080b6af82fccae4eb82f2b7f040ae7c78ec18523b3068574136668bd'
cmd=build info=image.stack index=1 name='local:latest' id='sha256:34c6a82094c31dcd49a2bae532de2fe9a0bc2d96d842e60473c0f9dff9e56332'
cmd=build state=image.inspection.done
cmd=build state=container.inspection.start
cmd=build info=container status=created name=dockerslimk_66_20210202062113 id=737640414a71772f212d29067a7fa7e29b81c6747309919ac87297b5cdae77b4
time="2021-02-02T06:22:13Z" level=error msg="channel.NewCommandClient: NewClient error = wait timeout"
time="2021-02-02T06:22:13Z" level=error msg="ipc.NewClient init error = wait timeout"
time="2021-02-02T06:22:13Z" level=fatal msg="docker-slim: failure" error="wait timeout" stack="goroutine 1 [running]:\nruntime/debug.Stack(0xc00008b740, 0x8, 0xc0002e9c40)\n\truntime/debug/stack.go:24 +0x9d\ngithub.com/docker-slim/docker-slim/pkg/util/errutil.FailOn(0xedd6a0, 0xc000184430)\n\tgithub.com/docker-slim/docker-slim/pkg/util/errutil/errutil.go:28 +0x54\ngithub.com/docker-slim/docker-slim/internal/app/master/commands/build.OnCommand(0xc0003121e0, 0x7ffc0749e8f5, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\tgithub.com/docker-slim/docker-slim/internal/app/master/commands/build/handler.go:299 +0x167f\ngithub.com/docker-slim/docker-slim/internal/app/master/commands/build.glob..func1(0xc0002d0580, 0x0, 0xc000153a60)\n\tgithub.com/docker-slim/docker-slim/internal/app/master/commands/build/cli.go:361 +0x1eb1\ngithub.com/urfave/cli.HandleAction(0xc55720, 0xdd9b40, 0xc0002d0580, 0xc0002d0580, 0x0)\n\tgithub.com/urfave/cli@v1.22.4/app.go:526 +0x11a\ngithub.com/urfave/cli.Command.Run(0xd97677, 0x5, 0x0, 0x0, 0x155c570, 0x1, 0x1, 0xdcdf56, 0x6c, 0x0, ...)\n\tgithub.com/urfave/cli@v1.22.4/command.go:174 +0x57a\ngithub.com/urfave/cli.(*App).Run(0xc0002d4380, 0xc0000ac000, 0xc, 0xc, 0x0, 0x0)\n\tgithub.com/urfave/cli@v1.22.4/app.go:279 +0x7c7\ngithub.com/docker-slim/docker-slim/internal/app/master.Run()\n\tgithub.com/docker-slim/docker-slim/internal/app/master/app.go:15 +0x54\nmain.main()\n\tgithub.com/docker-slim/docker-slim/cmd/docker-slim/main.go:8 +0x20\n" version="linux|Transformer|1.34.0|a5cb54043b3ab3cf747165aad745f19db680434e|2021-01-29_10:00:49PM"
ERROR: Job failed: exit code 1
```

Using the latest 1.34.0.

Any idea to fix this issue?

Cheers.
