### ISSUE TITLE
docker-compose `service network alias` values are created

### ISSUE THREAD

**Issue by slimdevl** [docker-slim/docker-slim#226]
Expected Behavior
=================

Service `alias` is populated in Networking setting of container Networking runtime when using `docker-compose` functionality.

It is common for docker-compose.yaml files to define a service, which references another `service name` (aka alias) in the same file. eg. In the example below, the alias reference is in the variable `GHOST_DATABASE_HOST=mariadb`

```yaml
version: '3.7'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_ghost
      - MARIADB_DATABASE=bitnami_ghost
  ghost:
    image: docker.io/bitnami/ghost:4
    ports:
      - '3500:2368'
    depends_on:
      - mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - GHOST_DATABASE_HOST=mariadb
      - GHOST_DATABASE_PORT_NUMBER=3306
      - GHOST_DATABASE_USER=bn_ghost
      - GHOST_DATABASE_NAME=bitnami_ghost
```
When listing the images using `docker inspect`, the `alias` should be listed. 

eg. 
```
docker inspect 78a772043c98
...
         "Image": "docker.io/bitnami/mariadb:10.3",
            ...
        "NetworkSettings": {
            ...
            "Ports": {
                "3306/tcp": null
            },
            ...
            "Networks": {
                "dsbuild_980205_20211001195213_default": {
                    "Aliases": [
                        "mariadb",
                        "78a772043c98"
                    ],
...
```
    
    
---
Actual Behavior
=================

No `Aliases` value with the service name is populated in the target service `Networks` values. 

```yaml
docker inspect ...
...
             "dsbuild_980205_20211001195213_default": {
                    "Aliases": [
                        "ccea60ef42e9"
                    ],
                }
                ...
```

---
Steps to Reproduce the Problem
===============================
  1. create a docker-compose.yaml file using the example configuration at the beginning of this report.
  1. pull both images
      ```bash
      docker pull docker.io/bitnami/mariadb:10.3
      docker pull docker.io/bitnami/ghost:4
      ```
  1. Run `docker-slim` using the following:
      ```bash
      docker-slim --debug build --show-clogs --http-probe-off --compose-file docker-compose.test.yaml --target-compose-svc ghost --publish-port '3500:2368' --env ALLOW_EMPTY_PASSWORD=yes --env GHOST_DATABASE_HOST=mariadb --env GHOST_DATABASE_PORT_NUMBER=3306 --env GHOST_DATABASE_USER=bn_ghost --env GHOST_DATABASE_NAME=bitnami_ghost --env GHOST_DATABASE_HOST=mariadb
      ```
  1. Open another terminal, and run `docker ps` and `docker inspect` for the `ghost` container instance.   

---
Specifications
=================
  - Version: 1.37.0
  - Platform: Ubuntu 21.04
