### ISSUE TITLE
gitlab ci timeouts on docker-slim build

### ISSUE THREAD

**Issue by grillazz** [docker-slim/docker-slim#348]
Expected Behavior
=================
As user I expect to be able to run docker-slim on Gitlab CI pipeline

---
Actual Behavior
=================
docker-slim build ending with error. 
Please find debug log below:

```
$ make slim TAG=${BUILD_TAG}
docker-slim --debug build \
			--in-container \
			--sensor-ipc-endpoint 172.17.0.2 \
			--include-path /usr/local/lib/python3.9 \
			--include-path /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 \
			--include-path /usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6 \
			--include-exe curl \
			--compose-env-file _docker-slim.env \
			--compose-file docker-compose.slim.yml \
			--target-compose-svc service-data-api \
			--dep-include-target-compose-svc-deps true \
			--publish-exposed-ports \
			--http-probe-exec service-data-api
....
make: *** [Makefile:67: slim] Error 1
Running after_script
00:01
Running after script...
$ docker rm -f $(docker ps | grep dockerslimk | awk '{print $1}') || true
cd2b9f727e80
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: exit code 1
```

---
Steps to Reproduce the Problem
===============================
1. `gitlab-ci.yml`
```
stages:
  - lint
  - build

before_script:
- docker info
- if [ -z "${BUILD_TAG+x}" ]; then export BUILD_TAG=$( [[ "$CI_COMMIT_TAG" == "" ]] && echo "$CI_COMMIT_SHORT_SHA" || echo "$CI_COMMIT_TAG" ); fi
- echo ${BUILD_TAG}

build:
  stage: build
  tags:
    - small
  services:
    - name: docker:20.10.11-dind
      command: [ "--registry-mirror", "https://docker-registry-cache.myloc.com:443" ]
  script:
    - ./tools/prepare_netrc.sh
    - make build TAG=${BUILD_TAG}
    - cat /etc/hosts
    - grep docker /etc/hosts | cut -f1
    - docker info
    - >
      apk add -u curl
      && curl -L -o ds.tar.gz https://downloads.dockerslim.com/releases/1.37.3/dist_linux.tar.gz
      && tar -xvf ds.tar.gz
      && mv dist_linux/docker-slim /usr/local/bin/
      && mv dist_linux/docker-slim-sensor /usr/local/bin/
    - cp .env _docker-slim.env
    - make slim TAG=${BUILD_TAG}
    - ./tools/push_slim_images.sh ${CI_REGISTRY} ${BUILD_TAG}
  after_script:
    - docker rm -f $(docker ps | grep dockerslimk | awk '{print $1}') || true
 ```
2. `docker-compose.slim.yml`
```
version: '3.8'

services:
  service-data-api-redis:
    image: redis:6.0.16
    command:
      - "/usr/local/etc/redis/redis.conf"
    environment:
      - TZ=${TZ}
    env_file:
      - .env
      - .secrets
    volumes:
      - ./etc/redis.conf:/usr/local/etc/redis/redis.conf

  service-data-api-redis-cluster:
    image: customer-registry.myloc.com/redis-trib:3.42.0
    env_file:
      - .env
      - .secrets
    command:
      - "create"
      - "service-data-api-redis:6379"
    depends_on:
      - service-data-api-redis

  service-data-api-db:
    image: customer-registry.myloc.com/postgresql:13.4-5
    ports:
      - "5432:5432"
    env_file:
      - .env
      - .secrets
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=${TZ}
    healthcheck:
      test:
        [
            "CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  service-data-api:
    image: service-data-api:${TAG}
    ports:
      - "8080:8080"
    env_file:
      - .env
      - .secrets
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/opt/services/mobile_biometry_data_api
    entrypoint: [
      "/opt/services/service_data_api/tools/wait-for-it.sh", "service-data-api-db:5432",
      "--",
    ]
    command: [
      "bash", "-c",
      "alembic upgrade head && uvicorn service_data_api.api.http.asgi:app
      --host 0.0.0.0 --port 8080
      --lifespan=on --use-colors --loop uvloop --http httptools
      --reload --log-level debug"
    ]
    depends_on:
      - service-data-api-db
      - service-data-api-redis-cluster
    healthcheck:
      test: ["CMD", "curl", "-sSf", "127.0.0.1:8080/status/live"]


  service-data-api-stream:
    image: service-data-api:${TAG}
    env_file:
      - .env
      - .secrets
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/opt/services/mobile_biometry_data_api
    entrypoint: [
      "/opt/services/mobile_biometry_data_api/tools/wait-for-it.sh", "service-data-api-db:5432",
      "--",
    ]
    command: [
      "python3", "src/service_data_api/app.py"
    ]
    depends_on:
      - service-data-api-db
      - service-data-api-redis-cluster
    healthcheck:
      test: ["CMD", "curl", "-sSf", "127.0.0.1:8080/status/live"]

volumes:
  service-data-api-data:
```
```
$ cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.2	docker 7d4612c1757d runner-n3aqvbyg-project-423-concurrent-0-662243acf6cd805c-docker-0
172.17.0.3	runner-n3aqvbyg-project-423-concurrent-0
$ grep docker /etc/hosts | cut -f1
172.17.0.2```


Quick summary of problem: No matter how I setup `DOCKER_HOST`or user dokcer-slim flags like `--sensor-ipc-endpoint` it is still trying to connect to `172.18.0.2` not to `172.17.0.2` which is actual docker host with error below: 
```time="2022-06-26T12:57:16Z" level=debug msg="channel.NewClient: net.DialTimeout(tcp,172.18.0.2:65501,15s) [time=1656248236643596371]"
time="2022-06-26T12:57:31Z" level=debug msg="channel.NewClient: (dial time = 15.000205811s) - connect error = dial tcp 172.18.0.2:65501: i/o timeout"
time="2022-06-26T12:57:31Z" level=debug msg="channel.NewClient: waiting before trying to connect again..."```
